server:
  port: 8085

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5436/inventory_service
    username: inventory_user
    password: inventory_password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
