server:
  port: 8083

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5435/product_service
    username: product_user
    password: product_password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
