server:
  port: 8086

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5437/order_service
    username: order_user
    password: order_password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
